### ISSUE TITLE
nvcc fatal   : Path to libdevice library not specified

### ISSUE THREAD

**Issue by madeofwin** [cudamat/cudamat#40]
Hi, I'm running a fresh ubuntu 14.04 installation with Cuda 6.5 and a GT650M. I downloaded the deb files from the official nvidia cuda site, added it via dpkg and executed 'sudo apt-get install cuda'. This installed Cuda 6.5 and nvidia-340 drivers. However, I'm running into troubles when I try to install cudamat by 'sudo python install setup.py', see the output:

running install
running bdist_egg
running egg_info
writing cudamat.egg-info/PKG-INFO
writing top-level names to cudamat.egg-info/top_level.txt
writing dependency_links to cudamat.egg-info/dependency_links.txt
reading manifest file 'cudamat.egg-info/SOURCES.txt'
writing manifest file 'cudamat.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'cudamat.libcudamat' extension
nvcc -I/usr/include/python2.7 -c cudamat/cudamat.cu -o build/temp.linux-x86_64-2.7/cudamat/cudamat.o -O --ptxas-options=-v --compiler-options '-fPIC'
nvcc fatal   : Path to libdevice library not specified
error: command 'nvcc' failed with exit status 1

I'm googling and trying different things for hours now and can't find a solutions. cuda examples are running without problems. Can you help me out?

**Comment by f0k** [comment]
Hmm, can you post your `/usr/local/cuda/bin/nvcc.profile` here? Do you have `/usr/local/cuda/nvvm/libdevice` available? I installed CUDA via the `.run` file, but your way of installing it is pretty much standard and should be supported as well.

**Comment by ziyuang** [comment]
I have the same issue so let me post mine:

nvcc.profile:

    TOP              = $(_HERE_)/..

    NVVMIR_LIBRARY_DIR = $(TOP)/nvvm/libdevice

    LD_LIBRARY_PATH += $(TOP)/lib:
    PATH            += $(TOP)/open64/bin:$(TOP)/nvvm/bin:$(_HERE_):

    INCLUDES        += "-I$(TOP)/$(_TARGET_DIR_)/include" $(_SPACE_)

    LIBRARIES       =+ $(_SPACE_) "-L$(TOP)/$(_TARGET_DIR_)/lib$(_TARGET_SIZE_)/stubs" "-L$(TOP)/$(_TARGET_DIR_)/lib$(_TARGET_SIZE_)"

    CUDAFE_FLAGS    +=
    OPENCC_FLAGS    +=
    PTXAS_FLAGS     +=

`libdevice`'s path:

    $ ls /usr/local/cuda/nvvm/libdevice
    libdevice.compute_20.10.bc  libdevice.compute_30.10.bc  libdevice.compute_35.10.bc

**Comment by f0k** [comment]
Hmm, my `nvcc.profile` is exactly the same, and `/usr/local/cuda/nvmm/libdevice` contains the same files. The only differences I see is that I don't have a fresh 14.04, but upgraded it from 12.04, and I only installed the driver via the `.deb` file and installed CUDA via the `.run` file instead (makes it easier to have several CUDA versions in parallel).

Ah wait, there's another difference. I always did a per-user install, so I never tried to compile via `sudo`. How did you ensure `root` can find `nvcc`? I have `/usr/local/cuda/bin` in my user's PATH, and the following compiles and installs cudamat fine:
```sudo PATH="$PATH" pip install .```

What does `which nvcc` and `sudo which nvcc` give you? Did you try to compile the CUDA examples as root?

You may also try to set `NVCCFLAGS` to what's suggested [in this Stack Overflow answer](http://stackoverflow.com/a/24804767), but there should be an easier way.

**Comment by ziyuang** [comment]
I think the `sudo` is the issue. I then added/changed the lines of `env_keep` and `secure_path` in `/etc/sudoers`, and the errors are gone.

**Comment by f0k** [comment]
> I then added/changed the lines of `env_keep` and `secure_path` in `/etc/sudoers`, and the errors are gone.

But why where the lines in `/etc/sudoers` wrong in the first place? If that was caused by installing CUDA, you should report that upstream to Nvidia, and note down what was needed to be changed here (so people from the future can read it). If it was your own mistake, please also note what you did and what you should have done instead, so others do not run into the same issue.

Just for reference, what I did after installing CUDA via the `.run` file was to:
1. add `export PATH=/usr/local/bin/cuda:"$PATH"` to my `~/.bashrc`, so `nvcc` is found for my user
2. create a file `/etc/ld.so.conf.d/cuda.conf` with a single line `/usr/local/cuda/lib64`, then run `sudo ldconfig`, so all compiled CUDA code will find the libraries at runtime (for all users; you can add it to `LD_LIBRARY_PATH` in your `~/.bashrc` if you cannot or do not want to set it system-wide)

I don't know if and how an installation via the `.deb` file differs, so it would be appreciated if you could briefly describe the post-installation steps to take!

**Comment by ziyuang** [comment]
I did all the `PATH`, `LIBRARY_PATH`, `LD_LIBRARY_PATH`, and `ldconfig` things when installing CUDA from the `.run` file like you said. But `sudo` changes the `PATH` for security reasons. To confirm, 

    $ python -c "import os;print(os.environ.get('PATH'))"
    $ /usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    $ sudo python -c "import os;print(os.environ.get('PATH'))"
    $ /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

while changing the `secure_path` line in `sudoers` can force `sudo` keeping the `PATH`.

**Comment by f0k** [comment]
> You may say this is my own mistake because it is actually not an issue of CUDAMat.

The real problem seem to be weird instructions circulating online on how to make `sudo nvcc` run. We could add a note on this to the cudamat installation instructions, but I don't think Linux-specific CUDA installation instructions belong there. For now, let's just have this Issue as a kind of FAQ entry.

**Comment by raulrm75** [comment]
I have faced this problem recently and solved by this way:

Inside a terminal: `sudo su`
(This make root the current user)
Inside the previous terminal: `export PATH=/usr/local/cuda-6.5/bin:$PATH`
(Where `/usr/local/cuda-6.5` is my current cuda installation. This makes nvcc visible by root)
Inside the previous terminal: `pip install .` or `pip3 install .`
(This will install cudamat for all users - python2 or python3 -)

**Comment by JingleiWang** [comment]
I cannot find the path /usr/local/cuda/nvmm/libdevice after installing cuda5.5 with .run.
When make the examples, I faced this problem nvcc fatal   : Path to libdevice library not specified.

**Comment by f0k** [comment]
Did you run `nvcc` as root or as a standard user? You should try as a standard user, with your `PATH` correctly set to include `/usr/local/cuda/bin`. Alternatively, you can edit `/etc/environment` to include that directory in the `PATH` of all users, similarly to [how you can configure `ldconfig`](https://github.com/cudamat/cudamat/issues/40#issuecomment-69580527) to make the `.so` files available to all users. That eliminates the need of setting any environment variables for your user. Try fiddling around with the setup a bit and report back, the discussion above never brought to light what exactly causes the error.

**Comment by roytseng-tw** [comment]
For my condition on ubuntu14.04, the problem is `sudo` will reset PATH variable (env_reset).
So wherever you put your PATH setting, it will just be reset when you use `sudo`.
possible solutions:
1. `sudo su` - make user as root, and also get your PATH back
2. change the setting in /etc/sudoers - not recommend
3. sudo "PATH=$PATH" <your commands>
    sudo env "PATH=$PATH" <your commands>

**Comment by JohnnyY8** [comment]
I also have the same problem when I make darknet on Ubuntu 14.04 with GPU K40 and CUDA 7.0.
![qq 20160317114452](https://cloud.githubusercontent.com/assets/12611573/13835730/c88ecc82-ec35-11e5-8721-703dbc6401d0.jpg)

I have tried many ways to solve it, but all did not work. 
My nvcc.profile is a little different with above {
TOP              = $(_HERE_)/..

NVVMIR_LIBRARY_DIR = $(TOP)/nvvm/libdevice

LD_LIBRARY_PATH += $(TOP)/lib:
PATH            += $(TOP)/open64/bin:$(TOP)/nvvm/bin:$(_HERE_):

INCLUDES        +=  "-I$(TOP)/$(_TARGET_DIR_)/include" $(_SPACE_)

LIBRARIES        =+ $(_SPACE_) "-L$(TOP)/$(_TARGET_DIR_)/lib$(_TARGET_SIZE_)/stubs" "-L$(TOP)/$(_TARGET_DIR_)/lib$(_TARGET_SIZE_)"

CUDAFE_FLAGS    +=
PTXAS_FLAGS     +=
}

And my env in /etc/profile is:
export CUDA_HOME=/usr/local/cuda
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
export PATH=$CUDA_HOME/bin:$PATH

Does anyone can help me? @f0k @ziyuang @roytseng-tw

**Comment by f0k** [comment]
You could try with `--dont-use-profile -ldir=/usr/local/cuda/nvvm/libdevice`. If this works, something is probably not installed correctly. Were you running `nvcc` directly as a standard user or as root?

**Comment by JohnnyY8** [comment]
Hello @f0k , thanks for your answer, but I do not understand what does "--dont-use-profile" mean and where should I use these arguments? When I am making darknet? 
As a standard user or root, running nvcc is ok, because I create a soft link to nvcc.
![qq 20160317192537](https://cloud.githubusercontent.com/assets/12611573/13844803/01cdb814-ec77-11e5-9a7c-3710f8610d7f.png)

**Comment by f0k** [comment]
>  I do not understand what does "--dont-use-profile" mean and where should I use these arguments?

You posted a screenshot of your `nvcc` call. You'll have to put these arguments somewhere such that they end up in the `nvcc` call. But see below.

> As a standard user or root, running nvcc is ok, because I create a soft link to nvcc.

I guess that's your mistake then. If you create a soft link at `/usr/local/sbin/nvcc`, it will probably look for `nvcc.profile` at `/usr/local/sbin/nvcc.profile`. You will have to run `nvcc` from its original location. Delete the softlink and make sure `sudo` inherits the environment from your user (https://github.com/cudamat/cudamat/issues/40#issuecomment-118790605).

**Comment by JohnnyY8** [comment]
It does work! Thank you so much! @f0k 
I remove the soft link about nvcc and add the original location to secure_path so that make successfully.
However, I want to know is there any better way to solve this problem? I have tried a method to make root path be the same as standard user path by modifying "Defaults !env_reset" in /etc/sudoers and adding " alias sudo='sudo env PATH=$PATH' " to ~/.bashrc. It also worked. But I do not know which is better or are there other ways?

**Comment by f0k** [comment]
Any way is fine, but from a point of security, it may be better to manually run `sudo env PATH=$PATH ...` whenever you need to install something as root that requires nvcc. This won't happen often anyway. Adding just the nvcc path to secure_path should be okay as well.

**Comment by JohnnyY8** [comment]
Yes, I think so. These two ways maybe okay, I just add nvcc path to the secure path because the secure is not important for us.
Anyway, thanks for everything profoundly! @f0k
