### ISSUE TITLE
Division by Zero during compilation

### ISSUE THREAD

**Issue by tristan-heuer** [cudamat/cudamat#48]
During installation I get these warnings:
cudamat_kernels.cu(771): warning: division by zero
cudamat_kernels.cu(747): warning: division by zero

Which correspond to the following line:
```C
target[targetRowI * nCols + colI] = sourceRowI==-1 ? (1.0/0.0 -1.0/0.0) : source[sourceRowI * nCols + colI];
```
Is that a mistake or some trick I don't know?

**Comment by f0k** [comment]
> Is that a mistake or some trick I don't know?

This seems to be fully intentional. If you follow [the full implementation](https://github.com/cudamat/cudamat/blob/master/cudamat/cudamat_kernels.cu#L727-749), it first sets the `sourceRowIndices` to `-1` whenever the source row is out of range, and in the line you mentioned it sets the target to `(1.0/0.0 -1.0/0.0)` when the source row is `-1`. `(1.0/0.0 -1.0/0.0)` gives `NaN`, so this fully matches [the documentation of `select_columns`](https://github.com/cudamat/cudamat/blob/master/cudamat/cudamat.py#L1134-1136). (Don't ask me about the kernel name...)

For ANSI C89, it seems there is no better way of generating a `NaN` value: http://stackoverflow.com/questions/6235847/how-to-generate-nan-infinity-and-infinity-in-ansi-c
If you find one, please feel free to send a pull request. Also feel free to send a PR that adds a comment to the two lines affected!
