### ISSUE TITLE
pow is modifying the matrix received as parameter

### ISSUE THREAD

**Issue by virilo** [cudamat/cudamat#50]
http://stackoverflow.com/questions/31102197/having-quite-different-results-in-matrix-multiplication-with-numpy-and-cudamat/31103304#31103304

I think this is not the desired behaviour, according to the pdf documentation: "...If no target is provided a new GPU matrix is allocated to store the result."

Thanks a lot for cudamat!!!

**Comment by f0k** [comment]
Sorry for the late reply, I've been abroad! I'm not sure which documentation you're referring to, the docstring for `pow` doesn't include this sentence:
https://github.com/cudamat/cudamat/blob/master/cudamat/cudamat.py#L1429-1449
Most methods and functions operate in-place if a separate target is not provided, there are only a few exceptions that operate out-of-place by default: (a) methods that cannot operate in-place because they return a differently shaped matrix (such as `transpose`, `get_row_slice`, `min`, `sum`), and (b) the `CUDAMatrix.sign` method.
I'm closing this issue because cudamat behaves as documented.
