### ISSUE TITLE
cm.dot with all-ones-matrix faster than matrix.sum

### ISSUE THREAD

**Issue by aerval** [cudamat/cudamat#74]
see the following code that calculates the rowsum of a matrix in two different ways
```python
import time
import numpy as np
import cudamat as cm
cm.cublas_init()

x, y = 100, 200
X = cm.CUDAMatrix(np.random.random([x,y]))
ones = cm.CUDAMatrix(np.ones([1,x]))
d1 = cm.empty([1,y])
d2 = cm.empty([1,y])

def test1():
    for i in range(10000):
        X.sum(0, target=d1)

def test2():
    for i in range(10000):
        cm.dot(ones, X, target=d2)

print "Timing sum"
t0 = time.time()
test1()
t1 = time.time()
print "Runtime sum: ", t1 -t0
print "--------------"
print "Timing cm.dot"
t0 = time.time()
test2()
t1 = time.time()
print "Runtime cm.dot ", t1 -t0

np.sum(d2.asarray() == d1.asarray())
```
that returns
```
Timing sum
Runtime sum:  0.40524315834
--------------
Timing cm.dot
Runtime cm.dot  0.171550035477
200
```
-> it is faster to multiply by a custom vector than summing

**Comment by f0k** [comment]
> it is faster to multiply by a custom vector than summing

On my desktop GPU, using `%timeit` in ipython, I get 49µs for the first and 37µs for the second variant. Increasing the dimensions to 1000x2000, it's 1.29ms against 1.11ms. That's fun, because `X.sum()` actually does a dot product with a vector of ones under the hood.

Investigating some further, the culprit is [`set_trans()`](https://github.com/cudamat/cudamat/blob/931ef92/cudamat/cudamat.py#L1244). Internally, cudamat stores a column vector of ones to use for reductions. When asked to do a row sum, this has to be used as a row vector, and it's solved by passing it as a transposed matrix:
```python
In [25]: ones.shape
Out[25]: (1, 1000)

In [26]: ones2 = cm.CUDAMatrix(np.ones([x,1]))

In [27]: ones2.set_trans(True)

In [28]: ones2.shape
Out[28]: (1000, 1)

In [29]: %timeit cm.dot(ones2, X, target=d2)
1000 loops, best of 3: 1.27 ms per loop
```
Now it's about as slow as `X.sum()`. The pity is that CUBLAS' `cublasSgemm` seems to take longer to process a transposed column vector than a non-transposed row vector, even though it could just use the exact same code path.

It should be possible to use reshaping instead, though. I'll try.

**Comment by f0k** [comment]
Found a better solution: Use gemv when either of the dot arguments is a vector. This is quite a bit faster than anything else. Feel free to have a look at #75, will merge tomorrow if there are no comments.

**Comment by aerval** [comment]
Interesting. It is faster for me now (39s and 14s in the tests above), though not as much as for you (although I deleted all generated files and reinstalled). Anyways, thanks for the great work.

**Comment by f0k** [comment]
> Interesting. It is faster for me now (39s and 14s in the tests above)

The timing for `.sum()` and the manual `dot()` should have been about the same with the new code. But I can reproduce your result. If you change the matrix size to `(1000, 2000)`, the difference is less noticeable. There is still a constant overhead for `.sum()` that is independent of the matrix size, about 10 to 20 µs per call on my computer. Most of this is caused by the `slice()` call on the preallocated `ones` vector. Avoiding this would require moving the `sum()` implementation to `cudamat.cu`, passing it the full `CUDAMatrix.ones` array and doing the correct `gemv` call. We only need to slice the `ones` to satisfy the dimensionality checks in `dot()`, otherwise we could use the array directly.

Feel free to send a PR if you want to squeeze out that last bit of performance. Make sure to address `add_sums()` as well, they could be handled in one go.
