### ISSUE TITLE
[Solved] Linux install fails: "unable to execute 'nvcc': No such file or directory"

### ISSUE THREAD

**Issue by jessexknight** [cudamat/cudamat#98]
Tried to install using:
```
sudo python setup.py install 
```

Got this error:
<details>
<summary>(click to expand)

<code>unable to execute 'nvcc': No such file or directory</code>
<code>error: command 'nvcc' failed with exit status 1</code>
</summary>

```
running install
running bdist_egg
running egg_info
writing cudamat.egg-info/PKG-INFO
writing top-level names to cudamat.egg-info/top_level.txt
writing dependency_links to cudamat.egg-info/dependency_links.txt
reading manifest file 'cudamat.egg-info/SOURCES.txt'
writing manifest file 'cudamat.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'cudamat.libcudamat' extension
nvcc -I/usr/include/python2.7 -c cudamat/cudamat.cu -o build/temp.linux-x86_64-2.7/cudamat/cudamat.o -arch=sm_52 -O --ptxas-options=-v --compiler-options=-fPIC
unable to execute 'nvcc': No such file or directory
error: command 'nvcc' failed with exit status 1
```
</details>

However, from [this post](https://askubuntu.com/questions/428234/nvcc-not-found-but-only-when-using-sudo) I replaced `nvcc` with `/usr/local/cuda-9.0/bin/nvcc` (full path to `nvcc` on my system) on lines `36` and `37` in `setup.py` and it worked :slightly_smiling_face: 

Feel free to add this workaround to `setup.py` or close as-is, but hopefully this may be helpful for future users.

System info:
```
Ubuntu 16.04.4 LTS
Python 2.7.12
```

**Comment by f0k** [comment]
Thank you for the report! If `nvcc` works, but `sudo nvcc` fails, then a likely cause is that you modified your `PATH` environment variable, which is not carried over to `sudo` for security reasons. Rather than modifying `setup.py` (which will require a different path depending on how CUDA was installed), you could do:
```bash
sudo PATH="$PATH" python setup.py install
```
or maybe:
```bash
sudo -E python setup.py install
```
The former will set the `PATH` environment for the python call to what you have locally, the latter will ask sudo to carry over the complete environment (which is considered unsafe and may not be permitted for every user).

**Comment by jessexknight** [comment]
Yes, my solution felt like a hack...

Thanks for the `sudo $PATH` info, definitely a better solution. I'm sure it will come in handy elsewhere too!
