### ISSUE TITLE
clang: error: cannot find libdevice for sm_61

### ISSUE THREAD

**Issue by mark0620** [cudamat/cudamat#99]
Hi
I'm new comer for the gpu and cuda
i installed cuda 10.1 and nvidia device driver recently

and I tried to compile the add.cu file with llvm clang with

`clang++ add.cu -o add_clang --cuda-gpu-arch=sm_61 -L/usr/local/cuda-10.1/nvvm -lcudart_static -ldl -lrt -pthread_`

as in the http://llvm.org/docs/CompileCudaWithLLVM.html 
but  there is error message like this

`clang: error: cannot find libdevice for sm_61. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
`

how can i fix debug this?

my gpu is geforce 1050 and use 18.04 ubuntu

**Comment by f0k** [comment]
Hey Mark!

> I tried to compile the add.cu file

But there is no `add.cu` file in cudamat -- are you talking about a personal project of yours? This issue tracker is about the cudamat Python module.

> my gpu is geforce 1050 and use 18.04 ubuntu

On Ubuntu, you can use nvcc with gcc. To install cudamat, just follow the directions in https://github.com/cudamat/cudamat/blob/master/INSTALL.md. For some general guidance on installing CUDA, see https://github.com/Lasagne/Lasagne/wiki/From-Zero-to-Lasagne-on-Ubuntu-14.04#nvidia-gpu-support-cuda. Hope this helps!

Closing this issue because it is not about cudamat, but feel free to still reply.
